### PR TITLE
Expand social networks partial

### PR DESCRIPTION
**Pull request by slavakisel**
Hello, @nurlansu . Some tiny improvements:

* Switch to secure links to social networks
* Allow users to add Medium and Telegram
* Upgrade font-awesome to 4.7

### CODE REVIEW

**Comment by kasradzenika** [comment]
cool, is there any way to fork from **hugo-sustain** AND also have these changes before the author pulls?

**Comment by slavakisel** [comment]
@kasradzenika yes. To do this make fork from my repo

**Comment by patrickderitter** [comment]
While I don't think specific edits need to be in the branch, perhaps we can render social links by using a data file instead of using the config.toml. Thoughts?

**Comment by slavakisel** [comment]
@patrickderitter I don't see any harm in using data file

**Comment by suyundukov** [comment]
Nice, thanks for this 👍

**Pull request merged**
